pipeline {
  agent { label 'docker' } 
  
  tools{
    maven 'maven 3.6.1'  
  }
  stages{
    stage("build"){
      when{
        changeset "**/worker/**"
      }
      steps{
        echo 'Compiling worker app'
        container('jnlp'){
            sh 'cd worker; env; mvn compile'
        }
      }
    }

    stage("package"){
      when{
        changeset "**/worker/**"
      }
      steps{
        container('jnlp'){
          sh 'cd worker; mvn package -DskipTests'
          sh 'ls -lah; ls -lah target'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
        container('kaniko'){
          sh """
              ls -lah; 
          """
        }
      }
    }

    
  }
  post{
    always{
      echo 'Building pipeline for worker is completed..'}
    }
  }
