pipeline {
  agent { label 'docker' } 

  stages{
    stage("build"){
      tools{
        maven 'maven 3.6.1'  
      }
      when{
        changeset "**/worker/**"
      }
      steps{
        container('jnlp'){
          sh 'cd worker; mvn compile;'
        }
      }
    }

    stage("test"){
      tools{
        maven 'maven 3.6.1'  
      }
      when{
        changeset "**/worker/**"
      }
      steps{
        container('jnlp'){
          sh 'cd worker; mvn clean test;'
        }
      }
    }

    stage("packaging"){
      tools{
        maven 'maven 3.6.1'  
      }
      when{
        changeset "**/worker/**"
      }
      steps{
        container('jnlp'){
          sh 'cd worker; mvn package -DskipTests'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
      }
    }

    stage("build-and-push-image"){
      when{
        changeset "**/worker/**"
      }
      steps{
        container('kaniko'){
          sh 'ls -lah; env;'
          sh 'cd worker; ls -lah; /kaniko/executor --context `pwd` --verbosity debug --destination harbor1.btech.id/library/worker:${GIT_COMMIT:0:7} --destination harbor1.btech.id/library/worker:latest'
        }
      }
    }

    stage("deploy-to-staging"){
      when{
        changeset "**/worker/**"
      } 
      steps{
        container('jnlp'){
          sshagent(credentials: ['ssh-private-key-lb']) {
            sh '''
                echo ${ref##*/};
                [ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
                ssh-keyscan -t rsa,dsa 10.81.81.21 >> ~/.ssh/known_hosts
                ssh root@10.81.81.21 ls -lah /root/deploy/worker
                ssh root@10.81.81.21 "cd /root/deploy/worker; helm upgrade worker . --version ${GIT_COMMIT:0:7} --set image.tag=${GIT_COMMIT:0:7} -n default"
            '''
          }
        }
      }       
    }
  }
  post{
    always{
      echo 'Pipeline Complete'
    }
  }
}



